# Generated by Django 3.2.15 on 2022-10-10 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='down_vote',
            field=models.ManyToManyField(null=True, related_name='ans_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answers',
            name='up_vote',
            field=models.ManyToManyField(null=True, related_name='ans_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
