# Generated by Django 3.2.15 on 2022-10-10 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20221010_1751'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('user', 'question')},
        ),
    ]
